# Describes the format for available statistic import services

import_from_file:
  fields:
    filename:
      required: true
      example: "statisticdata.tsv"
      selector:
        text:
    timezone_identifier:
      required: true
      example: "Europe/Vienna"
      default: "Europe/Vienna"
      selector:
        text:
    delimiter:
      required: false
      example: \t
      default: \t
      selector:
        select:
          custom_value: true
          options:
            - '\t'
            - ";"
            - ","
            - "|"
    decimal:
      required: true
      example: false
      default: false
      selector:
        boolean:

create_fitness_component:
  name: Discover Fitness Tracker
  description: Discovers a fitness tracker device for later configuration through the integration setup flow
  fields:
    component_name:
      required: true
      name: Component Name
      description: Unique identifier for the fitness tracker (alphanumeric and underscores only)
      example: "my_fitness_tracker"
      selector:
        text:
    vendor:
      required: true
      name: Vendor
      description: The vendor/manufacturer name of the fitness tracker
      example: "Generic Fitness Tracker"
      selector:
        text:
    device_info:
      required: false
      name: Device Info
      description: Additional device information (model, manufacturer, software/hardware versions)
      example: |
        {
          "model": "FT-1000",
          "manufacturer": "Fitness Corp",
          "sw_version": "1.0.0",
          "hw_version": "2.0"
        }
      selector:
        object:
    entities:
      required: true
      name: Entities
      description: List of fitness data entities to track (steps, heart rate, etc.)
      example: |
        [
          {
            "name": "daily_steps",
            "friendly_name": "Daily Steps",
            "state_class": "total_increasing",
            "icon": "mdi:foot-print"
          },
          {
            "name": "heart_rate",
            "friendly_name": "Heart Rate",
            "state_class": "measurement",
            "icon": "mdi:heart-pulse"
          }
        ]
      selector:
        object:
